version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        patterns:
          - "webpack"
          - "webpack-cli"
          - "copy-webpack-plugin"
